In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/ntaganiraktheos/country-dataset/Country Schools.csv

**Read the dataset**

In [2]:
df = pd.read_csv("/kaggle/input/datasets/ntaganiraktheos/country-dataset/Country Schools.csv")
print("Dataset shape:", df.shape)
df.head()

Dataset shape: (50, 8)

,SNO,TOTALSCHOOLS,TotalSchoolsInstalled,SchoolsPending,PercentageInstalled,InstalledLDDs,InstalledTDDs,FID
0,TURKANA,358.0,37.0,321.0,10.34%,3744.0,74.0,1
1,HOMA BAY,875.0,552.0,323.0,63.09%,22982.0,1104.0,2
2,WEST POKOT,498.0,242.0,256.0,48.59%,15114.0,484.0,3
3,KITUI,1238.0,1200.0,38.0,96.93%,42162.0,2400.0,4
4,TANA RIVER,159.0,143.0,16.0,89.94%,7415.0,286.0,5

## 1.Initial analysis

In [3]:
print("\nData types:")
display(df.dtypes.rename("data_type").to_frame())

Data types:

                      data_type
SNO                      object
TOTALSCHOOLS            float64
TotalSchoolsInstalled   float64
SchoolsPending          float64
PercentageInstalled      object
InstalledLDDs           float64
InstalledTDDs           float64
FID                       int64

In [4]:
print("\nNumerical summary:")
display(df.describe().T)

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
TOTALSCHOOLS,48.0,905.375000,3079.865641,93.0,271.75,422.5,637.00,21729.0
TotalSchoolsInstalled,48.0,609.541667,2078.968965,8.0,161.25,314.5,420.25,14629.0
SchoolsPending,48.0,295.833333,1009.291416,4.0,53.25,130.5,247.75,7100.0
InstalledLDDs,48.0,30150.750000,102851.947880,606.0,6289.00,14165.0,23215.00,723618.0
InstalledTDDs,48.0,1219.083333,4157.937929,16.0,322.50,629.0,840.50,29258.0
FID,50.0,25.500000,14.577380,1.0,13.25,25.5,37.75,50.0

In [5]:
print("\nCategorical summary:")
display(df.describe(include=["object"]).T)

Categorical summary:

                    count unique      top freq
SNO                    48     48  TURKANA    1
PercentageInstalled    48     48   10.34%    1

In [6]:
missing = df.isna().sum().sort_values(ascending=False)
missing_pct = (df.isna().mean() * 100).sort_values(ascending=False)
missing_summary = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct.round(2)
})
display(missing_summary[missing_summary["missing_count"] > 0].head(30))

                       missing_count  missing_percent
SNO                                2              4.0
TOTALSCHOOLS                       2              4.0
TotalSchoolsInstalled              2              4.0
SchoolsPending                     2              4.0
PercentageInstalled                2              4.0
InstalledLDDs                      2              4.0
InstalledTDDs                      2              4.0

**After initial inspection, the FID column has 2 more rows over other columns**